__pycache__/
.pytest_cache/
.venv/
/build
*.egg-info/
/stac_test_catalogs/
/.env

/.vscode
/Makefile
/docker-compose.yml
/Dockerfile.test
/Dockerfile.test.dockerignore
/httpd.conf
/locustfile.py

/stac_test_tools/
/test